### ISSUE TITLE
Ability to automatically fix linting errors

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_lint#1013]
It might be useful for lints to include [text changes](https://github.com/denoland/deno_ast/pull/63) in the lint diagnostic that would fix the diagnostic. For example, `no-unused-var` could return text changes that would remove unused imports.

This could then be used by a `deno lint --fix` command.

**Comment by kitsonk** [comment]
We should consider how we can leverage this properly in the lsp.  I believe currently the only quick fixes are to insert comments to ignore the lint error, would be good to support more useful/intelligent fixes.

**Comment by dsherret** [comment]
@kitsonk oh yeah didn't think about that. That would definitely be desired. I guess it should probably have the ability to return multiple possible solutions as a fix and they should be given a description. It could use the first one for `deno lint --fix` and then present all the possible options to someone in the editor.

**Comment by kitsonk** [comment]
Good idea.  Using roughly the pattern of the [code action](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction) from the LSP protocol would make the most sense.  While it doesn't have to be exactly 1-1, there should be a method on whatever structure to be able to convert it to an LSP code action.

This would also be a good way of structuring them for something like `deno lint --check` which would give you a preview of what changes would be done with `deno lint --fix`?
