### ISSUE TITLE
Output in compact format

### ISSUE THREAD

**Issue by hadriann** [denoland/deno_lint#1077]
I am using the Node.js binding (@node-rs/deno-lint) and am having a hard time integrating it with vim. It would help a lot if deno-lint had a way of controlling the output, such as the "--format compact" option in eslint. So, besides the pretty multiline colorized output that it now gives, it would be great (for integrating with other tools) to also have a plain text basic output format. For example, the compact output of eslint may be something like:

```
/path/to/file.js: line 10, col 20, Error - Unnecessary semicolon. (no-extra-semi)
/path/to/file.js: line 12, col 22, Warning - Missing semicolon. (semi)
```

**Comment by bartlomieju** [comment]
Makes sense, PRs are welcome

**Comment by brenelz** [comment]
Took a bit of a stab at this. If you have feedback let me know
