### ISSUE TITLE
no-self-assign rule grammar

### ISSUE THREAD

**Issue by tdillon** [denoland/deno_lint#1080]
The grammar of the help text seems off.  Should it be `made` instead of `make`?

https://github.com/denoland/deno_lint/blob/190a5e09332f8aaf4c8375fc3312e265961c9630/src/rules/no_self_assign.rs#L39

**Comment by magurotuna** [comment]
Yes, `made` sounds even better here to me too. Are you interested in fixing it? Otherwise I'll do, though feel free to work on it :) If you are interested, please leave a comment prior to starting to avoid conflict.

**Comment by tdillon** [comment]
I'll work on this issue.
