### ISSUE TITLE
Is it appropriate to use MediaType to check file types in `src/rules` ?

### ISSUE THREAD

**Issue by hirasawayuki** [denoland/deno_lint#1083]
Is it appropriate to use MediaType instead of filename when checking file types in `src/rules` ?

https://github.com/denoland/deno_lint/blob/55a3d5b6eb6beacd5782134aa764ea89f792136f/src/rules/no_namespace.rs#L40

If checking file type using MediaType is more appropriate, I will fix this code.

Related issues: #672

**Comment by magurotuna** [comment]
Good catch, that sounds like the way to go. Please go ahead if you're interested in working on it.
