### ISSUE TITLE
prefer-primordials: add check for `Promise.all`

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno_lint#1095]
https://github.com/denoland/deno/pull/16326

This PR has introduced `SafePromiseAll` which is a safe version of `Promise.all`. It would be nice if `prefer-primordials` could check for this.

Also, in my opinion, it would be much better if `PromisePrototypeThen` (and other similar stuff) could be checked by the linter.
My rudimentary idea is that we have the linter check for all `.then(...)` and warn them. Obviously this approach would produce lots of false positives, i.e. the linter would warn the call `.then(...)` even if this then method is not for Promise.
That said, I believe false positives are much better than false negatives in this case. When false positives occur we can suppress them, saying "hey linter, trust me, this is a false positive." However, when it comes to false negatives, we can never notice that there is problematic code that's prone to pollution from malicious users.

**Comment by petamoriken** [comment]
> My rudimentary idea is that we have the linter check for all `.then(...)` and warn them. Obviously this approach would produce lots of false positives, i.e. the linter would warn the call `.then(...)` even if this then method is not for Promise.
That said, I believe false positives are much better than false negatives in this case. 

I am going to create a PR that solves this.

I have created a PR for getter properties (#1114), and I believe that the methods can be checked in the same way.
