### ISSUE TITLE
Feature: guard-for-in

### ISSUE THREAD

**Issue by petamoriken** [denoland/deno_lint#1103]
In the for-in loop, it is necessary to check whether the property is owned by the object or not. How about introducing ESLint's [guard-for-in](https://eslint.org/docs/latest/rules/guard-for-in) in dlint as well?

related: https://github.com/denoland/deno/pull/17139

**Comment by bartlomieju** [comment]
Sounds good, would you be interested in opening a PR @petamoriken?

**Comment by petamoriken** [comment]
@bartlomieju OK, I'll try it 😄
