### ISSUE TITLE
Docs: Add a label to show which config is ON by default/what value it uses

### ISSUE THREAD

**Issue by babakfp** [denoland/deno_lint#1208]

**Comment by thegaryroberts** [comment]
In these docs it mentions it is recommended by default: https://docs.deno.com/runtime/manual/tools/linter#configuration
but no idea how to enable all rules (especially if they don't have a tag).

**Comment by bartlomieju** [comment]
The list of all the rules is available at https://lint.deno.land/. Let me know if that doesn't cover your needs, but I'm gonna close this one for now.
