### ISSUE TITLE
Rule semiColons for Deno lint

### ISSUE THREAD

**Issue by castrogarciajs** [denoland/deno_lint#1216]
Hello team Deno,

Is there some configuration so that the Deno linter marks the use of semicolons as something not viable for the code?
I was on the Deno lint site but couldn't find a similar rule.

Thank you for read 🦕.

**Comment by bartlomieju** [comment]
No, there's no such rule. There's a configuration in `deno fmt` to decide if you want semicolons or not: https://docs.deno.com/runtime/manual/tools/formatter#configuration
