### ISSUE TITLE
Website: Going to lint rule `no-console` via diagnostic url displays nothing

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_lint#1237]
```
> deno lint
error[no-console]: `console` usage is not allowed.
   --> V:\dax\src\command.ts:775:11
    | 
775 |           console.log("HERE");
    |           ^^^^^^^

  docs: https://lint.deno.land/#no-console
```

https://lint.deno.land/#no-console

Seems related to "show all rules"

**Comment by hashrock** [comment]
I'm struggling to find an easy fix because there's no way to determine the hash of a URL on the server.

Instead, I've come up with the idea of preparing individual pages for each rule. If we do that, we can also automatically expand the details when accessed.

**Comment by hashrock** [comment]
Added single rule route with #1246

Can you please change the URL on the CLI side? @dsherret
