### ISSUE TITLE
relax the `no-console` rule within the `Deno.test` calls or the whole test file

### ISSUE THREAD

**Issue by king8fisher** [denoland/deno_lint#1243]
If it is totally harmless to reference console within the boundaries of tests, that would be awesome.

I guess, tests can also call helper functions, so may be this will have to affect whole test files. Only if there is no way to import any helper functions or classes located in the test files by regular files.

**Comment by dsherret** [comment]
I personally like the lint rule for `Deno.test` calls. Sometimes if I accidentally leave a console.log there then the test output gets noisy so it's nice to have the lint rule help me clean those up. I just add a `// deno-lint-ignore no-console` if I really want to do that.

**Comment by king8fisher** [comment]
Feels like an unnecessary addition after all!
