### ISSUE TITLE
feature request: `no-sloppy-imports`

### ISSUE THREAD

**Issue by Colt45s** [denoland/deno_lint#1293]
Thank you for the many wonderful improvements!

Automatically generated code using npm libraries and similar tools may sometimes use Node.js' import syntax.

I want `deno lint` to be run to resolve sloppy imports.

**Comment by dsherret** [comment]
I've been working on this in the CLI actually. Follow this issue for updates: https://github.com/denoland/deno/issues/22844#issuecomment-1989103409

**Comment by Colt45s** [comment]
Thank you!!
