### ISSUE TITLE
Add Deno scripts for formatting and linting Rust code

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#131]
`tools/format.ts` should run:
```
rustfmt --check examples/dlint/main.rs
rustfmt --check src/lib.rs
deno fmt --check benchmarks/benchmarks.ts
```

`tools/lint.ts` should run:
```
cargo clippy --all-targets --release --locked -- -D clippy::all
target/release/examples/dlint benchmarks/benchmarks.ts
```

CI script should be updated to run those scripts

**Comment by iykekings** [comment]
@bartlomieju there's no tools folder, should I add it? I want to work on this. I can easily adapt deno tools

**Comment by bartlomieju** [comment]
> @bartlomieju there's no tools folder, should I add it? I want to work on this. I can easily adapt deno tools

Yeah, go ahead!
