### ISSUE TITLE
Unsafe precondition violated when running tests

### ISSUE THREAD

**Issue by nathanwhit** [denoland/deno_lint#1310]
Running tests in debug mode (just `cargo test`) errors out with

```
thread 'js_regex::reader::tests::at_test_es_compliance' panicked at library/core/src/panicking.rs:219:5:
unsafe precondition(s) violated: invalid value for `char`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
```

CI runs with `cargo test --release` and so stdlib assertions aren't executed.

**Comment by nathanwhit** [comment]
Presumably the issue is in this unsafe block (the only one in the crate) https://github.com/nathanwhit/deno_lint/blob/b09c72a0c91eee66a4982bead818c13437f54453/src/js_regex/reader.rs#L126-L131

**Comment by 0f-0b** [comment]
This was previous reported in #1052.

**Comment by nathanwhit** [comment]
> This was previous reported in #1052.
Oh thanks, didn't see that one! I'll close this then
