### ISSUE TITLE
Move schema to CLI repo

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_lint#1369]
https://github.com/denoland/deno_lint/pull/1335/files

Reasons:

1. We have CLI specific rules.
1. If an update happens here then it takes effect immediately for users.
1. We should move towards having the schemas in github releases so the specific deno version someone uses is the schema they use.

cc @nayeemrmn

**Comment by bartlomieju** [comment]
This is now done in https://github.com/denoland/deno_lint/pull/1378
