### ISSUE TITLE
Disable all non `recommended` rules for now

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_lint#140]
I think while we have no config options we should disable all non `recommended` rules because they can give false positives very often (eg `eqeqeq`, https://discordapp.com/channels/684898665143206084/684911491035430919/720016434314608710)

:heavy_check_mark: are all rules which are part of `eslint:recommended` or `typescript-eslint:recommended` 
:sauropod: are all rules not present in `eslint` or `typescript-eslint`

- `ban-ts-comment` :heavy_check_mark:
- `ban-ts-ignore` :sauropod:
- `ban-untagged-ignore` :sauropod:
- `ban-untagged-todo` :sauropod:
- `constructor-super` :heavy_check_mark:
- `default-param-last`
- `eqeqeq`
- `explicit-function-return-type`
- `for-direction` :heavy_check_mark:
- `getter-return` :heavy_check_mark:
- `no-array-constructor`
- `no-async-promise-executor` :heavy_check_mark:
- `no-case-declarations` :heavy_check_mark:
- `no-class-assign` :heavy_check_mark:
- `no-compare-neg-zero` :heavy_check_mark:
- `no-cond-assign` :heavy_check_mark:
- `no-debugger` :heavy_check_mark:
- `no-delete-var` :heavy_check_mark:
- `no-dupe-args` :heavy_check_mark:
- `no-dupe-keys` :heavy_check_mark:
- `no-duplicate-case` :heavy_check_mark:
- `no-empty` :heavy_check_mark:
- `no-empty-character-class` :heavy_check_mark:
- `no-empty-function` :heavy_check_mark:
- `no-empty-interface` :heavy_check_mark:
- `no-empty-pattern` :heavy_check_mark:
- `no-eval`
- `no-ex-assign` :heavy_check_mark:
- `no-explicit-any` :heavy_check_mark:
- `no-func-assign` :heavy_check_mark:
- `no-misused-new` :heavy_check_mark:
- `no-namespace` :heavy_check_mark:
- `no-new-symbol` :heavy_check_mark:
- `no-obj-call` :heavy_check_mark:
- `no-octal` :heavy_check_mark:
- `no-prototype-builtins` :heavy_check_mark:
- `no-setter-return` :heavy_check_mark:
- `no-sparse-array` :heavy_check_mark:
- `no-this-alias` :heavy_check_mark:
- `no-throw-literal`
- `no-unsafe-finally` :heavy_check_mark:
- `no-unsafe-negation` :heavy_check_mark:
- `no-var`
- `no-with` :heavy_check_mark:
- `prefer-namespace-keyword` :heavy_check_mark:
- `require-yield` :heavy_check_mark:
- `single-var-declarator` :sauropod:
- `triple-slash-reference` :heavy_check_mark:
- `use-isnan` :heavy_check_mark:
- `valid-typeof` :heavy_check_mark:

**Comment by bartlomieju** [comment]
I'm open to that as long as they are still tested
