### ISSUE TITLE
Finish scope analysis

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#160]

**Comment by disizali** [comment]
@bartlomieju Do you plan to work on this soon?
I can work on some parts if you don't have enough time ...

**Comment by bartlomieju** [comment]
@disizali go ahead, this week I'm working mostly on Deno.

A good start would be to:
- ensure all types of scopes are created when needed
- all bindings are added for each type of scope - warning: this is quite complex for `Pat` (func arguments)

After we got those two working we could think about discovering references to bindings.

**Comment by bartlomieju** [comment]
@disizali I just checked and it seems that `Loop` scope is never constructed - ie. `for (...)`, `for .. of ...` and `for .. in ..`. So tests added in #180 might not catch everything. I'll try to handle `Loop` scope this weekend

**Comment by disizali** [comment]
@bartlomieju Before you get started, I had an active branch about adding loop scoops.
I'll open a PR in a few minutes.

**Comment by bartlomieju** [comment]
Done in #267
