### ISSUE TITLE
.deno-lint configuration file (suggestion)

### ISSUE THREAD

**Issue by ardyfeb** [denoland/deno_lint#166]
User can enable / disable rules, but not customize the rules https://github.com/denoland/deno/issues/1880#issuecomment-601303015

**Comment by bartlomieju** [comment]
I'm not 100% sold on the idea of config file, but we can prototype this functionality and use it in `dlint` example first for some bike-shedding.

**Comment by bartlomieju** [comment]
Ref https://github.com/denoland/deno_lint/issues/367

**Comment by bartlomieju** [comment]
Superseded by https://github.com/denoland/deno/issues/11686 and https://github.com/denoland/deno/pull/11776
