### ISSUE TITLE
Feature Request: Webpack Loader for Deno Lint

### ISSUE THREAD

**Issue by jetfontanilla** [denoland/deno_lint#169]
I think it would be great if we have a webpack loader for deno lint, and would be configurable to break the build whenever it encounters a lint error

example webpack configuration:
```
{
                    test: /\.(ts|js)$/,
                    enforce: "pre",
                    loader: "deno-lint-loader",
                    options: {
                        emitErrors: true,
                        failOnHint: true
                    }
                }
```

**Comment by Brooooooklyn** [comment]
@bartlomieju  Could you please assign this issue to me? I will try to implement it with [napi-rs](https://github.com/napi-rs/napi-rs)

**Comment by bartlomieju** [comment]
I'm not very familiar with webpack loaders so I might need a bit more context. 

There's two possible ways I see to handle that:
- call external binary - this can be either `deno lint` or some custom built binary like [`examples/dlint`](https://github.com/denoland/deno_lint/tree/master/examples/dlint)
- compile linter to WASM lib

**Comment by bartlomieju** [comment]
@Brooooooklyn sure, thanks for pointing out `napi-rs`

**Comment by Brooooooklyn** [comment]
Working on https://github.com/napi-rs/node-rs/pull/61

**Comment by Brooooooklyn** [comment]
latest update

I got around `20x` performance vs `eslint`

```
@node-rs/deno-lint x 2,172 ops/sec ±0.91% (91 runs sampled)
eslint x 56.42 ops/sec ±8.18% (59 runs sampled)
Lint benchmark bench suite: Fastest is @node-rs/deno-lint
```

**Comment by bartlomieju** [comment]
@Brooooooklyn sounds great! Looking forward for development!

**Comment by Brooooooklyn** [comment]
Published [@node-rs/deno-lint@0.1.0](https://www.npmjs.com/package/@node-rs/deno-lint)

**Comment by Brooooooklyn** [comment]
> Latest update, I got around 40x performance vs eslint

It's a wrong result due to wrong implementation....

The real benchmark result:

```
@node-rs/deno-lint x 885 ops/sec ±1.26% (92 runs sampled)
eslint x 118 ops/sec ±4.97% (78 runs sampled)
Lint benchmark bench suite: Fastest is @node-rs/deno-lint
```

And it was just represent for the performance between `eslint` and `@node-rs/deno-int` in programmably usage.

**Comment by jetfontanilla** [comment]
awesome work, thanks!

my next question is if I want to configure individual rules for the loader, how should i go about it?

**Comment by Brooooooklyn** [comment]
> if I want to configure individual rules for the loader, how should i go about it

I'm planning to implement `.denolintconfig` feature, maybe relate to https://github.com/denoland/deno_lint/issues/166.
I will implement the feature in [node-rs](https://github.com/napi-rs/node-rs) project. And if my implement meets the requirement of `deno_lint` itself, I'm happy to migrate it into `deno_lint` then.

**Comment by bartlomieju** [comment]
@Brooooooklyn very nice binding! I'd be willing to link it in the README once it's somewhat stable. Please let me know if you need help with integration.

**Comment by bartlomieju** [comment]
@Brooooooklyn am I right in assumming that your project keep up to date with release of `deno_lint`? Should we link it now in the README?

**Comment by Brooooooklyn** [comment]
Yes I’m keeping up to date the `@node-rs/deno-lint`, I think it’s cool to add it to README. 🎉

**Comment by bartlomieju** [comment]
Thanks, added to README in https://github.com/denoland/deno_lint/pull/815. Gonna close this issue now.
