### ISSUE TITLE
How to use this outside Deno?

### ISSUE THREAD

**Issue by dalisoft** [denoland/deno_lint#191]
Hi @denoland and it's team and contributors.

Thanks for good work, but i'd like to test this, but it's possible to use outside Deno?

**Comment by bartlomieju** [comment]
Hey @dalisoft you can try out `deno_lint` by building the included example called `dlint`:
```
$ cargo build --all-targets

$ target/debug/examples/dlint file1.ts file2.ts
```
Please keep in mind that it's really an example demonstrating `deno_lint` and is not really configurable

**Comment by dalisoft** [comment]
Thanks a lot. I’ll try
