### ISSUE TITLE
LintDiagnostic should implement "Serialize" trait

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#253]
Required for https://github.com/denoland/deno/pull/6940

It should probably be gated behind `json` Cargo feature as it will introduce dependency on `serde`

**Comment by souldzin** [comment]
@magurotuna, I see you have :eyes: on this issue. Are you planning on picking it up? I might be able to hop on it in a day or two :smile:

**Comment by magurotuna** [comment]
@souldzin If I work on this, it will be this weekend. 
So it would be better for you to pick it up👍

**Comment by magurotuna** [comment]
Ah... I'm not sure I understand what you said correctly. (sorry for my poor English skill)
Would you like to take this issue yourself @souldzin ? Or do you want me to pick it up? (of course I can do if you want.)

**Comment by souldzin** [comment]
> Ah... I'm not sure I understand what you said correctly. (sorry for my poor English skill)

It seems like we're talking about the same thing :smile:

> Would you like to take this issue yourself @souldzin ?

I'm happy to. I'll probably be able to hop on it before the weekend. I'll let you know if anything changes. 👍

**Comment by magurotuna** [comment]
I see!

**Comment by humancalico** [comment]
@souldzin Are you still working on it? Can I pick it up?

**Comment by souldzin** [comment]
Sorry for the late reply. This week ended up being busier than I hoped :(

Thanks for taking care of this!
