### ISSUE TITLE
Ignore specific rule for an entire file

### ISSUE THREAD

**Issue by sumitgoelpw** [denoland/deno_lint#255]
There seems to be a way to ignore linting a file, but I cannot find anything to ignore specific rule(s) for an entire file. What would be the best way to do that?

**Comment by bartlomieju** [comment]
`deno_lint` does not provide a way to ignore certain diagnostic in whole file.

**Comment by sumitgoelpw** [comment]
Thanks for the response, @bartlomieju. Can this be considered a feature request?

**Comment by bartlomieju** [comment]
Sure, I've added appropriate label.

**Comment by bartlomieju** [comment]
This issue came up in `vscode_deno` as well (https://github.com/denoland/vscode_deno/pull/162#issuecomment-687577199). I think we can go ahead and add support for it.

**Comment by bartlomieju** [comment]
I will add support for this functionality - needed for https://github.com/denoland/deno_lint/pull/304 in `std/`
