### ISSUE TITLE
Question: Why does deno not use `get_recommended_rules`?

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno_lint#277]
`deno_lint` provides `get_recommended_rules` function as public, so that users of `deno_lint` can get information about available implemented rules.
However, this function seems not to be used by `deno`, and `deno` has [its own `get_rules` function](https://github.com/denoland/deno/blob/master/cli/lint.rs#L99-L152).

Is this a temporary measure until `deno_lint` implements all of the recommended rules? In other words, once `deno_lint` has the all recommended rules implemented, `deno` will use `get_recommended_rules`  instead of `get_rules`?
I'm curious about the reason why `deno` is not using `get_recommended_rules` now.

**Comment by bartlomieju** [comment]
@magurotuna `no-const-assign`/`no-ex-assign` seem to be a bit broken 😅  and that's why I used it. Thanks for pointing this out, I forgot to update that list for some time now.

I think we could remove those rules from `get_recommended_rules` and switch Deno to use it.

**Comment by magurotuna** [comment]
@bartlomieju Thanks for the quick answer! I understand the reason.
Are you going to work on removing those rules and switching? I'd like to work on it myself if you don't mind, because it would be a suitable task for my first contribution to `deno` :)

**Comment by bartlomieju** [comment]
@magurotuna sure, that'd be very helpful, thanks!

**Comment by magurotuna** [comment]
OK, I'll do it :+1: 
Closing this issue because my question is resolved.

**Comment by bartlomieju** [comment]
@magurotuna actually it seems that those rules will be fixed in #279 can you hold off a bit longer before working on the PR?

**Comment by magurotuna** [comment]
@bartlomieju I see!

**Comment by magurotuna** [comment]
I see #279 was merged into master. Can I start working on switching Deno to use get_recommended_rules instead of get_rules without removing any rules?

**Comment by bartlomieju** [comment]
@magurotuna go ahead, although I expect there's gonna be quite a few error when running `cargo test lint` in `deno` repo

**Comment by bartlomieju** [comment]
@magurotuna unfortunately I need to release a cascade of new crates to make upgrade possible

**Comment by magurotuna** [comment]
@bartlomieju I see, thanks so much for letting me know!

**Comment by bartlomieju** [comment]
Done!
