### ISSUE TITLE
no-unexpected-multiline creates conflicts with deno fmt

### ISSUE THREAD

**Issue by qu4k** [denoland/deno_lint#291]
This discussion originated from the deno discord:

### Conflict

This code

```typescript
const typescript: Template = {
  filename: "denon.config.ts",
  source: String.raw`import { DenonConfig } from "https://deno.land/x/denon@${VERSION}/mod.ts";

const config: DenonConfig = {
  scripts: {
    start: {
      cmd: "deno run app.ts",
      desc: "run my app.ts file",
    },
  },
};

export default config;`,
};
```

Gets formatted (with `deno fmt`) to:

```typescript
const typescript: Template = {
  filename: "denon.config.ts",
  source: String.raw
    `import { DenonConfig } from "https://deno.land/x/denon@${VERSION}/mod.ts";

const config: DenonConfig = {
  scripts: {
    start: {
      cmd: "deno run app.ts",
      desc: "run my app.ts file",
    },
  },
};

export default config;`,
};
```

And `deno lint --unstable` throws:

```bash
(no-unexpected-multiline) Unexpected newline between template tag and template literal
    `import { DenonConfig } from "https://deno.land/x/denon@${VERSION}/mod.ts";
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/rossi/dev/orgs/denosaurs/denon/src/templates.ts:32:5
```

### Possible solution

1. Remove the `no-unexpected-multiline` as it's scope is more towards formatting than linting
2. Patch `deno fmt` so no newline is added between a template tag and a template literal

### Opinion

Personally I am in favour of solution number 1 as I think this rule does not belong to the `deno lint` ruleset. It's more suited as a formatting rule. Or to put it in @lucacasonato words:

> i think this rule should be removed from our set. it is a stupid rule imo

😃

**Comment by bartlomieju** [comment]
It might be a bug in rule implementation. To be verified.

**Comment by dsherret** [comment]
@bartlomieju what's the purpose of this rule since `deno fmt` handles this automatically? Is it for people who use deno_lint without a formatter?

**Comment by bartlomieju** [comment]
@dsherret no concrete purpose, it was blindly ported from ESLint. I'm happy to remove it if it's handled by formatter.

**Comment by bartlomieju** [comment]
Removed in https://github.com/denoland/deno_lint/pull/300
