### ISSUE TITLE
Deno lint doesn't recognize function arguments object

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno_lint#317]
If you have a function and want to use the arguments object, deno lint will show `(no-undef) arguments is not defined`. To pass lint I switched to using `(...args: any[])` in my call signature and `// deno-lint-ignore no-explicit-any` to ignore my use of any.

**Comment by bartlomieju** [comment]
I think function scopes should have implicit `arguments` binding defined.

CC @kdy1
