### ISSUE TITLE
Add prefer-const rule

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#337]
This is one of most useful rules, we should definitely add it.

https://eslint.org/docs/rules/prefer-const

**Comment by magurotuna** [comment]
Agreed, `prefer-const` is actually one of the most useful rules. It seems very hard to implement, but I'd like to try.

**Comment by bartlomieju** [comment]
@magurotuna great! Most likely this rule will require use of scopes, @kdy1 could you provide some guidance?

**Comment by kdy1** [comment]
You can implement this using two visitors.

First one should collect information from variable declarations and assignments.

From second one, you visit variable declarations with `var` or `let` and if collected usage does not contain any re-assignment, you can report an error.


As all identifiers are unique with respect to span hygiene, you don't need complex scope analysis. It's ok to store all variables in a single hashmap, aka `HashMap<Id, T>` where `Id` is from `swc_ecmascript::utils`.

**Comment by magurotuna** [comment]
@kdy1 Thanks a lot for the very clear guidance!
