### ISSUE TITLE
Support linting scripts

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#366]
Currently `deno_lint` works only on ES modules. 

In `deno` repo all runtime code is written as scripts, it'd be great if we could use `deno_lint` to lint those files as well. 

This will require change to `LintRule` trait - instead of `lint_module()` there should be `lint_program()` method, as well as new method on `Linter` itself to treat loaded file as script instead of module. 

Not sure about integration with `deno lint` subcommand yet. Would be great if we could infer if file is script/module (alternatively we could use some directive to inform linter about it: `// deno-lint script` / `// deno-lint module`) 

CC @lucacasonato

**Comment by nayeemrmn** [comment]
> Not sure about integration with `deno lint` subcommand yet. Would be great if we could infer if file is script/module (alternatively we could use some directive to inform linter about it: `// deno-lint script` / `// deno-lint module`)

Only modules are supported in user space so the subcommand should continue to assume modules. Plus there's no way to infer between scripts and modules until https://github.com/tc39/proposal-modules-pragma passes... but that proposal puts scripts as the default. Not very good for us.

**Comment by bartlomieju** [comment]
@nayeemrmn thanks for pointing this out. Then I think `// deno-lint-pragma script` would be the way to go, we won't have to document it for `deno lint`, but use it only internally in tests.

**Comment by bartlomieju** [comment]
> @nayeemrmn thanks for pointing this out. Then I think `// deno-lint-pragma script` would be the way to go, we won't have to document it for `deno lint`, but use it only internally in tests.

Just realized that this approach might not work - we first need to parse the file to check for such comment...

**Comment by bartlomieju** [comment]
Waiting on https://github.com/swc-project/swc/pull/1189

**Comment by nayeemrmn** [comment]
@bartlomieju We lint `cli/rt` with `dlint` now. I don't think we did anything though... it seems the scripts are valid modules as they are written.

Either way, can this be closed? There's no other motivation to support scripts.

**Comment by lucacasonato** [comment]
Indeed resolved through https://github.com/denoland/deno_lint/pull/484

**Comment by bartlomieju** [comment]
FYI discovering whether a file is a script/module is now handled implicitly by SWC when using `parse_program()` API.
