### ISSUE TITLE
Documentation website

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#368]
I did some exploring on how we could provide documentation website. 

First idea was to use `docs.rs` which we'd get for free using module docs, but there are a few drawback to that approach:
a) not really well suited for end-user, there's a lot of unnecessary noise for lint rule documentation
b) `docs.rs` markdown cannot render code block for other languages than Rust

Other approach that [RSLint](https://github.com/RDambrosio016/RSLint) takes is using `cargo xtask` in CI to generate documentation from rule definitions and outputs it to `.md` files. This approach has its advantages, but I'm not sure it's worth creating Markdown files while docs already live alongside rule definition.

@lucacasonato and I discussed creating documentation using [`dext.ts`](https://github.com/lucacasonato/dext.ts). In this variant we could levarage linter binary itself by:
a) firstly calling `deno lint --rules` to get list of available rules and generate list of static sites
b) secondly calling `deno lint --rules <rule name>` to obtain raw markdown that would be used as static data to generate pages for each rules

This approach would completely decouple documentation generation from `deno_lint`'s CI. Additionally we could provide in-console documentation by using terminal markdown renderer. 

Happy to hear opinions on this subject.

Ref https://github.com/denoland/deno_lint/issues/159

**Comment by RDambrosio016** [comment]
RSLint's docgen does more than only write to md files, it also generates a table of config info with their type and any documentation they have on them, it then crawls rule tests and generates "more examples" sections from it, and finally it adds a source hyperlink and adds the rule to the table at the group's top level. That approach means we have user facing docs and rustdoc docs as you can see on the [rslint_core docs](https://docs.rs/rslint_core/0.1.1/rslint_core/groups/errors/index.html). deno lint's approach is fine for in-terminal, but that bloats the binary a little bit with the docstrings, and it makes any rustdoc documentation impossible. Needing the binary to generate a docs website seems a little odd to me.

**Comment by bartlomieju** [comment]
@RDambrosio016 thanks for stopping by :)

> RSLint's docgen does more than only write to md files, it also generates a table of config info with their type and any documentation they have on them, it then crawls rule tests and generates "more examples" sections from it, and finally it adds a source hyperlink and adds the rule to the table at the group's top level. 

Thanks for detailed explanation. Crawling tests seems interesting, but how does it decide which examples should go into docs given there's a lot of them?

> That approach means we have user facing docs and rustdoc docs as you can see on the rslint_core docs

That's nice, although the problem described in point b) still stands:
> docs.rs markdown cannot render code block for other languages than Rust

That's why I'm not super keen on using `docs.rs` for lint rules documentation.

> deno lint's approach is fine for in-terminal, but that bloats the binary a little bit with the docstrings, and it makes any rustdoc documentation impossible

I guess you're referring to the fact that documentation is done in `docs()` method - I'm not entirely sold on this idea yet and I expect it might change if this approach ends up being to cumbersome.

> Needing the binary to generate a docs website seems a little odd to me.

That's actually the same way we generate documentation in https://doc.deno.land/ - by invoking Deno binary to do the heavy lifting.

Thanks for your feedback!

**Comment by RDambrosio016** [comment]
> but how does it decide which examples should go into docs given there's a lot of them?

It just takes the first invocation of the macro and puts them all in, it doesnt really matter how many there are since they are put in expandable blocks, and you can tell it to ignore a test with `/// ignore`

> That's nice, although the problem described in point b) still stands:

Which is why we use `ignore` and not `js`, which yields rust syntax highlighting, its not the best but its way better than nothing. Then the docgen just translates to js, and for in-terminal explain we use rslint_lexer which [has one dark pro highlighting built in](https://github.com/RDambrosio016/RSLint/blob/master/rslint_lexer/src/highlight.rs)

> That's why I'm not super keen on using docs.rs for lint rules documentation.

It looks fine if you use ignore instead of js, the only thing is it kind of lags a little bit when you run cargo test on rslint_core

**Comment by bartlomieju** [comment]
Website is now set up at https://lint.deno.land/

This issue is resolved for now.
