### ISSUE TITLE
Implement RuleVisitor

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#412]
Given problems from #330 it's clear that `swc_ecma_visit::Visit` is not a great choice for implementing rule.
We should implement `RuleVisitor` trait that sits on top of `swc_ecma_visit::Visit` and unconditionally visits
whole tree recursively. It would provide the same API but instead of requiring implementor to visit child nodes
it should visit them automatically after calling `RuleVisitor::visit_<node_name>`.

CC @magurotuna @kdy1

**Comment by kdy1** [comment]
Maybe I can provide one from swc_ecma_visit. (Or I can add feature to the proc macro)

**Comment by bartlomieju** [comment]
@kdy1 that would be very useful, if you're fine with having it in SWC, I might look into implementing that in the coming days.

**Comment by kdy1** [comment]
I'm fine with it. Actually I think it's a must for visitor generator, but I was busy working on the type system.

Btw, I'm not sure about the name. Also, there are two way to go. First one is reusing `Visit` by creating a wrapper struct which accepts `Visit` as a type parameter will be enough.
Second way is creating a new trait - namely `VisitAll`.

I think first one would be better, but I'd like to hear opinion about it.

**Comment by bartlomieju** [comment]
@kdy1 both of the solutions sound good to me, I guess it's a matter of your preference and which one would produce smaller binary ;)

**Comment by kdy1** [comment]
I've created `VisitAll` and `VisutAllWith`

See: https://swc.rs/rustdoc/swc_ecma_visit/trait.VisitAll.html
