### ISSUE TITLE
Provide better hint in camelcase rule

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno_lint#416]
Given the code:

```ts
const { no_camelcased = false } = bar;
``` 

when applying `camelcase` rule to this code, we get a hint that looks like:

```
Consider replacing `{ no_camelcased }` with `{ no_camelcased: noCamelcased }`
```

It's a little confusing because `= false` is gone. 
So, we would be happier if hint was as follows:

```
Consider replacing `{ no_camelcased = false }` with `{ no_camelcased: noCamelcased = false }`
```

_Originally posted https://github.com/denoland/deno_lint/pull/302#issuecomment-712252783_

**Comment by bartlomieju** [comment]
Done in #480

**Comment by magurotuna** [comment]
@bartlomieju 
This issue is different from what's done in #480 - This is about assignment pattern (for providing default value) in destructuring assignments (typically appearing in _left-hand_ side of assignment expressions), while in #480, I fixed only about object literals (typically appearing in _right-hand_ side of assignment expressions).
