### ISSUE TITLE
no-constant-condition doesn't handle else case

### ISSUE THREAD

**Issue by kmurph73** [denoland/deno_lint#417]
<img width="785" alt="deno_lint_bug" src="https://user-images.githubusercontent.com/74591/96515665-926d0500-121a-11eb-87b2-903012f711a3.png">

**Comment by magurotuna** [comment]
Thanks for the bug report. I'll look into that.

**Comment by magurotuna** [comment]
@kmurph73 
That false negative will be fixed in the next release of Deno because it was addressed a few days ago :) #404 
In addition to that, I have just added some more tests to make sure that `else-if` is handled correctly. #418

**Comment by kmurph73** [comment]
@magurotuna Good to know, thanks for the tests & looking into it.
