### ISSUE TITLE
AggregateError is not defined deno_lint(no-undef)

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno_lint#419]
Seeing this in VS Code while using the official Deno extension with `"deno.lint": true` in `.vscode/settings.json`:

<img width="648" alt="Screen Shot 2020-10-20 at 07 24 35" title="VS Code theme: https://marketplace.visualstudio.com/items?itemName=hedinne.popping-and-locking-vscode" src="https://user-images.githubusercontent.com/868251/96585870-cb05f080-12a5-11eb-8b71-49f3364e6a14.png">

Pretty sure it's a bug:

```ts
console.log(typeof AggregateError); // function
```

**Comment by lucacasonato** [comment]
Do you have a larger code snippet? This is not enough to tell what is happening.
