### ISSUE TITLE
Add lint rule to check unversioned imports from deno.land/x/

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#443]
We should add a rule that verifies that imports from `deno.land/x/` are versioned.

It should have `recommended` and `deno` tags.
 

CC @lucacasonato

**Comment by nayeemrmn** [comment]
-1 for special handling of any host. This should be a plugin.

**Comment by kdy1** [comment]
How about checking if the url contains semver?
I think it would work for most of CDNs.
Also, it would emit errors for using files from githubusercontent.com

**Comment by bartlomieju** [comment]
Deno's LSP already handles this, closing.
