### ISSUE TITLE
Thanks for making this :-) 

### ISSUE THREAD

**Issue by matklad** [denoland/deno_lint#46]
Not really an issue, just a :+1: on the push to a self-contained TypeScript toolchain :) I spend a significant amount of time babysitting TypeScript build for vscode extension for rust-analyzer, and I am looking forward to a (distant) future, where I need only `deno`, and don't have a 100k lockfile just to make sure I use `;` consistently.

**Comment by bartlomieju** [comment]
@matklad thank you for kind words :) there's still long way to go for this project, but we'll get there eventually.

Thanks you for rust-analyzer! It's been a game changer!
