### ISSUE TITLE
Consider using "rslint_errors" crate for diagnostics

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#482]
RSLint's facilities for creating diagnostics are much more advanced than deno_lint's. We should consider using [`rslint_errors`](https://crates.io/crates/rslint_errors) crate for creating diagnostics. I'm a bit worried about dependencies and how that would impact main `deno` binary, but it's worth exploring. 

CC @RDambrosio016 @magurotuna

**Comment by RDambrosio016** [comment]
Currently rslint_errors relies on rowan for rowan/rslint specific span stuff, i may be able to feature gate it soon (kind of busy with other rslint stuff right now), other than that, it relies on the following crates:
- unicode-width (for vendored codespan)
- text-diff for automatic suggestion labeling
- rslint_text_edit as the backing structures for ^
- termcolor and colored for standard cross-platform error rendering
  the vendored codespan renderer uses termcolor and colored is used to keep my sanity while making alternative formatters :)

**Comment by bartlomieju** [comment]
Actually I think we should try to use `swc_common::errors` first because it's already one of our dependencies. 

Skimming through docs there's https://docs.rs/swc_common/0.10.5/swc_common/errors/struct.Diagnostic.html that seems to be suitable for our use case. The only missing things is that `Diagnostic` doesn't have `Serialize` trait.

**Comment by bartlomieju** [comment]
Current diagnostic system works fine, once we find ourselves lacking in its capabilities we'll reconsider.
