### ISSUE TITLE
[bug] walk_expression is only called for top level expressions.

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_lint#5]
`walk_expression` is not being called for function arguments, if statement tests, variable assignments, switch cases and all other non top level expressions.

The same is true for many other properties.

**Comment by kevinkassimo** [comment]
Yeah I also noticed this. I changed a bit to make it work with #3

**Comment by bartlomieju** [comment]
Replaced with `swc_ecma_visit` https://github.com/swc-project/swc/pull/743
