### ISSUE TITLE
Add require-await rule 

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#503]
[`require-await`](https://eslint.org/docs/rules/require-await) was used in `deno` repository and helped to catch inefficiencies in code. We should add this rule and make it `recommended`. 

CC @kdy1 can you look into it?

**Comment by magurotuna** [comment]
Looking at ESLint's implementation, this rule doesn't seem so much difficult to port to me.

**Comment by bartlomieju** [comment]
> Looking at ESLint's implementation, this rule doesn't seem so much difficult to port to me.

Sorry @magurotuna I've missed your comment. If you want to work on this rule I'm more than happy :)
