### ISSUE TITLE
deno lint allow snake_case

### ISSUE THREAD

**Issue by andykais** [denoland/deno_lint#513]
Hi, so I have a deno project that I chose to write in snake case. I have just started integrating deno lint & deno test, and deno lint isnt really usable because it just outputs a ton of linter errors stating that I should use camelCase instead of snake_case. So my options are to either:
a) give up on the linter
b) add ignore line comments on every line that uses a snake_case variable

I would love the ability to enable/disable certain linter rules, but before asking for that feature I want to know what deno's philosophy on linting is. Does deno want to be an opinionated authority on linter rules (like standardjs), or does it want to be an extendable linter?

If it is meant to be extendable, it would be awesome to declare certain linter rules as disabled for a whole project. I say disabled instead of enforcing snake case, because I will always have to use camelCase on imported libraries and the standard lib. (e.g. `Deno.consoleSize` is camelCase).

**Comment by andykais** [comment]
thank you, I was not aware of of the deno_lint repo. It looks like my concern is already addressed!

**Comment by magurotuna** [comment]
@andykais Good to hear that :)

@bartlomieju I think this issue can be closed as resolved.
