### ISSUE TITLE
Using `--ignore` Still 'Checks' The Specified Files

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno_lint#525]
To reproduce, do the follwing:

```
$ touch app.ts
$ time deno lint --unstable # make note of the time
$ npm i express
$ time deno lint --unstable --ignore='node_modules' # make note of the time
```

Whilst deno lint wont check those files, due to the time difference it seems like still iterates over the ignored dirs/files but just doesn't add them to the 'linterrors' array

Using deno v1.5.2

**Comment by bartlomieju** [comment]
This is being worked on in https://github.com/denoland/deno/pull/8040

**Comment by ebebbington** [comment]
Oh :D I'm sure i mentioned it before but couldn't find a ref - assumed it would be an issue with the deno_lint repo. I will close this then, thanks @bartlomieju
