### ISSUE TITLE
[require-await] no need for await in a return statement

### ISSUE THREAD

**Issue by oganexon** [denoland/deno_lint#569]
The `require-await` rule was recently added but it does not help when I return a promise.

```ts
async function foo() {
  const result = await Promise.resolve(3);
  return result;
}

async function bar() {
  return foo();
}
```

This works fine with `foo` but not with `bar`. Yet `bar` returns a promise, it is thus a valid async function.

```
(require-await) Async function 'bar' has no 'await' expression.
async function bar() {
^^^^^^^^^^^^^^^^^^^^^^
  return foo();
^^^^^^^^^^^^^^^
}
^
```

Unfortunately this would require some type checking to enforce, which `deno_lint` can't do at the moment.

**Comment by Soremwar** [comment]
`async` is only required when you use `await` inside that same function, not when you are returning an async value. If you were to remove `async` from `bar` you would still return a promise that is the result of `foo`.

**Comment by oganexon** [comment]
You're absolutely right. Thanks !
