### ISSUE TITLE
Try re-implementing some rule using dprint-swc-ecma-ast-view 

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno_lint#571]
https://github.com/dsherret/dprint-swc-ecma-ast-view

@dsherret created this awesome crate that wraps swc's AST, which allows navigating AST more freely than swc's visitor we're currently using.
I think it will make lots of rules easy to implement, e.g. `no-await-in-loop` in nearly the same way as RSLint does. So I'd say it's worth trying to use it.

**Comment by dsherret** [comment]
There's a few small details I need to work out, but it's basically ready. I'm going to spend another weekend on it and then it should be good for use!

**Comment by dsherret** [comment]
@magurotuna ok, should be good to use in 0.3.0 I believe. Let me know if you have any suggestions for anything or find any bugs.

**Comment by magurotuna** [comment]
@dsherret Great! I'll take a stab at it :)

**Comment by magurotuna** [comment]
I'm kind of busy recently, which prevents me from trying to implement it. Although I don't have time to implement, I elaborate on how to make it in my mind. I'll manage it as soon as possible :)

**Comment by bartlomieju** [comment]
@magurotuna should we still keep this issue open?

**Comment by magurotuna** [comment]
sorry, didn't notice the mention. There are still lots of rules that need to be changed to use ast-view. I'll open an issue to keep track of progress.
