### ISSUE TITLE
no-undef gets triggered after destructure parameters on functions

### ISSUE THREAD

**Issue by Soremwar** [denoland/deno_lint#596]
I found a quite weird corner case here

If I were to create a function with the following structure

```ts
export const checkAdminAccess = async (
  { a }: { a: number },
  next: () => Promise<void>,
) => {}
```

Deno lint will warn me that next is not defined, however doing any changes to the function parameters (such as changing the first parameter for a non-destructurable one) will remove the warning

**Comment by magurotuna** [comment]
Minimal reproduction I've found is:

```ts
const f = (
  { a }: Foo,
  b: boolean,
) => {};
```

```
(no-undef) b is not defined
  b: boolean,
  ^^^^^^^^^^
    at /home/yusuktan/Repos/github.com/magurotuna/deno_lint/foo.ts:6:2

Found 1 problem
Checked 1 file
```

If we add an additional parameter `c` to the function like:

```ts
const f = (
  { a }: Foo,
  b: boolean,
  c: number,
) => {};
```

output changes to:

```
(no-undef) b is not defined
  b: boolean,
  ^^^^^^^^^^
    at /home/yusuktan/Repos/github.com/magurotuna/deno_lint/foo.ts:6:2

(no-undef) c is not defined
  c: number,
  ^^^^^^^^^
    at /home/yusuktan/Repos/github.com/magurotuna/deno_lint/foo.ts:7:2

Found 2 problems
Checked 1 file
```

And if we place `{ a }: Foo` between `b: boolean` and `c: number` like:

```ts
const f = (
  b: boolean,
  { a }: Foo,
  c: number,
) => {};
```

then we get:

```
(no-undef) c is not defined
  c: number,
  ^^^^^^^^^
    at /home/yusuktan/Repos/github.com/magurotuna/deno_lint/foo.ts:7:2

Found 1 problem
Checked 1 file
```

From these results, it seems like parameters placed after destructuring pattern trigger the lint error unexpectedly.
