### ISSUE TITLE
Remove Camel Case Rule

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno_lint#610]
I'd like to propose the removal of this rule from deno lint.

I've seen some others complain of this rule as well in the past. It causes issues for some users and is one of the least impactful rules. This is a stylistic decision and in my opinion should not be in a linter. I hope deno lint can stick to rules for common issues and errors, and give you back a report with line numbers that you can use to fix things. Leave style out entirely and let that be handled by deno fmt.

With the recent update, I now have hundreds of errors inside my typings folder because the third party API is built in python so it has snake_case. Now I have hundreds of errors, because of valid typings.

In my opinion, this rule should be a plugin that someone adds in optionally as a stylistic addition.

**Comment by Soremwar** [comment]
Second this, or please add it to a list of rules that you can enforce optionally

**Comment by 00ff0000red** [comment]
It is a stylistic decision, and that is one of the main points of a linter, to enforce a code style across a code base, but snake_case is hands down my favorite, regardless of whether it's being used in a camalCase language such as JavaScript, or not.

**Comment by bartlomieju** [comment]
The discussion about it has been quite heated over at Discord, but nothing changed since February and I believe everyone just accepted that `camelcase` is part of recommended rule set. 

I'm going to close this issue now. Feel free to comment with more arguments against it.
