### ISSUE TITLE
deno lint mis-parses private method parameters?

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno_lint#615]
Run the following through `deno lint`:
```js
class T {
  #foo(x, y) {}
  #bar(x, y) {}
}
```

`deno lint` claims that I have declared `x` and `y` twice, as if they were were properties, instead of parameters.

**Comment by magurotuna** [comment]
@kdy1 
It seems like this issue happens due to swc's bug; in the following snippet, both `x` have the same `Id` unexpectedly.

```ts
class T {
  #foo(x) {}
  #bar(x) {}
}
```

Could you take a look into it?

**Comment by kdy1** [comment]
@magurotuna I'll take a look.

**Comment by kdy1** [comment]
@magurotuna You are right. It was a bug of swc.
I fixed it with https://github.com/swc-project/swc/pull/1414.

But updating swc will need some work because I made one breaking change recently - `Ident` does not have `type_ann` anymore. If you are okay with it, I'll make a pr for upgrading swc.

**Comment by magurotuna** [comment]
@kdy1 
Great job!
At a glance, `type_ann` of `Ident` is being used currently (for instance: https://github.com/denoland/deno_lint/blob/main/src/rules/no_unused_vars.rs#L71), and I'm not sure whether there will be a workaround after `type_ann` is removed from `Ident`. But I'm willing to adjust deno_lint to the new version of swc.

**Comment by kdy1** [comment]
@magurotuna There's a new type named `BindingIdent` which is used by parameters or patterns and has `type_ann`.

See: https://docs.rs/swc_ecma_ast/0.39.0/swc_ecma_ast/struct.BindingIdent.html

> But I'm willing to adjust deno_lint to the new version of swc.

Then I'll focus on fixing bundler instead :). Thanks!
