### ISSUE TITLE
Add `no-deprecated-deno`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_lint#650]
This lint would error on all uses of the APIs that we are going to deprecate as per https://github.com/denoland/deno/issues/9795. The lint only has to appear on the most obvious cases (e.g. `new Deno.Buffer`, but not `const { Buffer } = Deno; new Buffer();`).

The lint rule should be `recommended`.

For Deno 1.9 the lint should highlight the following APIs:
- `Deno.Buffer`
- `Deno.readAll`
- `Deno.readAllSync`
- `Deno.writeAll`
- `Deno.writeAllSync`

Rule name is open for bikeshedding :-)

**Comment by magurotuna** [comment]
How about clarifying a little more by adding `api` as postfix like `no-deprecated-deno-api`?

Anyway, I would like to work on it :D

**Comment by lucacasonato** [comment]
Sounds good. Let's bike-shed the name in the PR.
