### ISSUE TITLE
Function parameters are not defined.

### ISSUE THREAD

**Issue by OverGlass** [denoland/deno_lint#658]
Hello 👋 
Deno lint say that my second destructuring assignment arguments is not defined.

Minimal reproduction :
```typescript
const foo = ([nb, min]: [number, number], [value, diff]: [number, number]) => "Hello Bug !"
```
![Deno Lint visual](https://i.ibb.co/QDrrk8L/Bug-Deno-Lint.png)

Thank's you :)

**Comment by magurotuna** [comment]
Thanks for reporting!
I can reproduce what you encountered in my environment:
```
deno 1.8.3 (release, x86_64-unknown-linux-gnu)
v8 9.0.257.3
typescript 4.2.2
```

But it seems like the bug disappeared in the latest deno_lint (which means the current main branch, 1a1718b). Therefore I think the fix will be included in the next release of Deno (probably in 4 or 5 days).

**Comment by lucacasonato** [comment]
Let's add a regression test for this case then.
