### ISSUE TITLE
`no-unused-vars` doesn't support JSX

### ISSUE THREAD

**Issue by Skalman** [denoland/deno_lint#663]
`no-unused-vars` emits an error for the following code, even though `React` is required.

```js
import React from "..."; // `React` is never used
export default <div />;
```

Not even when a function is explicitly used in a JSX tag does `no-unused-vars` understand what's going on: 

```js
import React from "..."; // `React` is never used
function Component() { return null; } // `Component` is never used
export default <Component />;
```

Unfortunately, I'll need to downgrade to Deno 1.8, where this rule wasn't enabled by default.

**Comment by magurotuna** [comment]
Thanks for reporting! That must be a bug. I'll dig into it.
