### ISSUE TITLE
`no-unused-vars` in constructor in declared classes

### ISSUE THREAD

**Issue by Skalman** [denoland/deno_lint#670]
`no-unused-vars` emits an error for the following code. This is probably not very common in regular TypeScript, but of course very common in type declaration files.

```ts
export declare class C {
    constructor(arg: string);
//              ^^^^^^^^^^^
//              `arg` is never used
}
```

**Comment by magurotuna** [comment]
@Skalman Thanks for reporting! That will be fixed by #673.
