### ISSUE TITLE
Use `MediaType` to determine if the file is JSX or not in `no-unused-vars`

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno_lint#672]
> This should work for a first pass, but ultimately this should use `MediaType` to determine if it is JSX or not. (remote files can be declared JSX by using `text/jsx` content-type.)

_Originally posted by @lucacasonato in https://github.com/denoland/deno_lint/pull/664#discussion_r615969757_

**Comment by bartlomieju** [comment]
Once https://github.com/denoland/deno_lint/pull/904 lands this will be possible by checking `context.media_type()` value when executing a rule.

**Comment by brenelz** [comment]
I think I can tackle this issue. I am learning Rust and this seems pretty straightforward

**Comment by bartlomieju** [comment]
Sounds good @brenelz
