### ISSUE TITLE
Add CLI parser

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#68]
It will take a few more months before linter is good enough to be shipped with `deno`. 

In the meantime we could still use it as a standalone binary for testing purposes. That means we need a CLI parser - we should use `clap` (because it's already used in Deno).

For starters CLI should only two situations:
- printing help - `dlint -h`, `dlint --help`, `dlint help`
- running linter on provided list of files - `dlint file.ts`, `dlint file2.ts`

**Comment by cknight** [comment]
As a thought, what about shipping it hidden/undocumented now in Deno, which is enabled only through an `-experimental` flag?  Might make dog-fooding easier.  You could even hook it into the CI running alongside eslint once it's robust enough (which it might already be?).  I'm guessing you would be more likely to get better engagement and feedback this way.  Looking forward to the final product!

**Comment by bartlomieju** [comment]
> As a thought, what about shipping it hidden/undocumented now in Deno, which is enabled only through an -experimental flag? Might make dog-fooding easier. 

@cknight that's the idea - probably we'll end up with `deno lint --unstable` for starters. Thinking about shipping it in Deno `v1.2.0`.

> You could even hook it into the deno CI running alongside eslint once it's robust enough (which it might already be?), continuously testing the functionality built to date (and testing the deno code base as well). 

That's a good idea. `deno_lint` is definitely not robust enough - we'll missing a lot of recommended rules from ESLint (#48) and there's also quite a few of them in typescript-eslint.

> I'm guessing you would be more likely to get better engagement and feedback this way. Looking forward to the final product!

We definitely want to get more eyes on this project. Thanks!
