### ISSUE TITLE
Allow caller to provide list of globals

### ISSUE THREAD

**Issue by ry** [denoland/deno_lint#680]
Deno CLI should provide the list of global variables to check, it should not be hardcoded in deno_lint.

When we added WebSocketStream support to deno, it required making a release to deno_lint: https://github.com/denoland/deno_lint/pull/679

**Comment by lucacasonato** [comment]
@ry `deno lint` does not use `no-undef` rule anymore, so globals are not used anymore. This is just because we use the `dlint` executable in CLI repo.

**Comment by magurotuna** [comment]
It looks like the main repo uses dlint v0.2.18 which is outdated. https://github.com/denoland/deno_third_party/tree/master/prebuilt
Additionally, the release of dlint executable doesn't follow the progress of deno_lint lib. So what we should do to address the issue are:

1. release the latest dlint executable (v0.4.0, in this version `no-undef` is disabled)
2. update dlint in deno_third_parth repo
3. submodule update in deno repo
