### ISSUE TITLE
Add rule disallowing prefixing of web APIs with `window`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_lint#682]
There should be a warning for `window.fetch`, recommending to replace with `fetch` or `globalThis.fetch` for compatibility between window, web workers, and service workers.

This should be limited to the known subset of APIs that are available in both the window, and workers.

**Comment by bartlomieju** [comment]
AFAIK `self` is valid in all of the contexts you enumerated.

**Comment by bartlomieju** [comment]
So I'm +1 on this rule, any suggestion to the name?

**Comment by lucacasonato** [comment]
`no-window-prefix`? (`self` prefix should be allowed)

**Comment by magurotuna** [comment]
@lucacasonato 
Is there a smart way to get "the known subset of APIs that are available in both the window, and workers"?

**Comment by lucacasonato** [comment]
You could parse `lib.deno.window` and `lib.deno.worker` and get the intersection of types from the two. Maybe an easy way would be to get `deno doc` json output from both and intersect the two.

**Comment by magurotuna** [comment]
That's great, thanks!
