### ISSUE TITLE
.tsx support

### ISSUE THREAD

**Issue by brandly** [denoland/deno_lint#710]
Hello! I'm excited by this project. I keep running it against various repos, and it fails on `.tsx` files. It seems like [there's some awareness](https://github.com/denoland/deno_lint/blob/c2f71275fbd38e71076146e34ff79aac77cf3f9f/src/rules/no_unused_vars.rs#L84-L88) of tsx files, but I can't tell if they're truly supported.

For example, if I run it against [some file](https://github.com/brandly/boof/blob/master/src/Tape.tsx#L30-L39), it fails as soon as it reaches the JSX syntax.

```
$ dlint run src/Tape.tsx
thread 'main' panicked at 'Failed to lint: SwcDiagnosticBuffer { diagnostics: ["Expected >, got className at src/Tape.tsx:30:9"] }', examples/dlint/main.rs:199:8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$ RUST_BACKTRACE=1 dlint run src/Tape.tsx   
thread 'main' panicked at 'Failed to lint: SwcDiagnosticBuffer { diagnostics: ["Expected >, got className at src/Tape.tsx:30:9"] }', examples/dlint/main.rs:199:8
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   4: rayon::iter::plumbing::bridge_producer_consumer::helper
   5: dlint::main
$ RUST_BACKTRACE=full dlint run src/Tape.tsx
thread 'main' panicked at 'Failed to lint: SwcDiagnosticBuffer { diagnostics: ["Expected >, got className at src/Tape.tsx:30:9"] }', examples/dlint/main.rs:199:8
stack backtrace:
   0:        0x10d96d3b4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7c9bbbcf55ac7d45
   1:        0x10d98785e - core::fmt::write::hc858fa51ad07feb2
   2:        0x10d96a326 - std::io::Write::write_fmt::h13e13e9932df1a87
   3:        0x10d96f2d9 - std::panicking::default_hook::{{closure}}::hca29e9daefd4910e
   4:        0x10d96edc0 - std::panicking::default_hook::h39360a887d72e62b
   5:        0x10d96f945 - std::panicking::rust_panic_with_hook::h4a0037861340f650
   6:        0x10d96f485 - std::panicking::begin_panic_handler::{{closure}}::hf455655e1cea0b96
   7:        0x10d96d818 - std::sys_common::backtrace::__rust_end_short_backtrace::hd403f11cffc53200
   8:        0x10d96f3ea - _rust_begin_unwind
   9:        0x10d9a5b4f - core::panicking::panic_fmt::hd58a9da5b3060524
  10:        0x10d9a5a55 - core::result::unwrap_failed::hb126e8c08461d543
  11:        0x10c78df11 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut::h5e353b340d75b5c1
  12:        0x10c79118f - rayon::iter::plumbing::bridge_producer_consumer::helper::ha629aa7f8af4b29b
  13:        0x10c7944eb - dlint::main::he37e579ff3da1906
  14:        0x10c769c1a - std::sys_common::backtrace::__rust_begin_short_backtrace::h4427ae0b9cf716a6
  15:        0x10c769c41 - std::rt::lang_start::{{closure}}::hbb960b91e5a64a4d
  16:        0x10d96fd94 - std::rt::lang_start_internal::h329e3030be70bf86
  17:        0x10c7959b9 - _main
```

Am I doing something wrong and we could report a better error message? Are `.tsx` not supported? Thank you!

### Version

`v0.5.0`

**Comment by bartlomieju** [comment]
Looks like a problem on our side, TSX is supposed to be supported (we got some tests that check it). It might either be a problem when parsing file extension or it's a bug in SWC. We'll investigate.

**Comment by magurotuna** [comment]
I think it's because the dlint binary has limited capabilities; it always parses the input programs as TypeScript so encountering TSX syntax causes a panic.
It would be good to have dlint check for file extensions so it can parse the program with appropriate parse config. I'll do it.

**Comment by bartlomieju** [comment]
> I think it's because the dlint binary has limited capabilities; it always parses the input programs as TypeScript so encountering TSX syntax causes a panic.
> It would be good to have dlint check for file extensions so it can parse the program with appropriate parse config. I'll do it.

Ah that makes sense, I was going through the linter logic trying to find where it misparses file extension. Thanks for looking into it Yusuke!

**Comment by brandly** [comment]
thanks for the quick fix!!
