### ISSUE TITLE
[feature-request] Quick Actions

### ISSUE THREAD

**Issue by somebody1234** [denoland/deno_lint#729]
the ability to ctrl+. then adding a deno-lint-ignore(-file) comment would be nice. currently I have to manually type it out, not sure if there's a better way

**Comment by magurotuna** [comment]
Yes that would be a nice feature we should have, and there's a draft PR for that: https://github.com/denoland/deno/pull/10627

**Comment by kitsonk** [comment]
Duplicate of denoland/deno#10122
