### ISSUE TITLE
Feature Request: lint rule for empty enums? (including const enums)

### ISSUE THREAD

**Issue by somebody1234** [denoland/deno_lint#745]
considering there's already a lint rule for empty interfaces, i think this would be not a bad idea at least

**Comment by bartlomieju** [comment]
`const enum` is not supported in Deno anyway, but I'm open to adding rule for empty enums.

**Comment by DmitryRomaniuk** [comment]
I'll pick up that issue :)

**Comment by satyarohith** [comment]
Closed by #848
