### ISSUE TITLE
Render hyperlinks in docs nicely to the terminal

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno_lint#761]
Currently, links in docs are rendered as they are, like `[foo](https://example.com)`.
(as we can see in https://github.com/denoland/deno_lint/pull/756#issuecomment-870692549)

This is not so bad, but some terminal emulators support hyperlinks (just like HTML `<a>` tag) as described in [this gist](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda). Probably we could make use of this feature in rendering rule docs to the terminal.

We don't have to worry about what would happen in terminals that don't support the feature, according to the gist:

> Any terminal that correctly implements OSC parsing according to ECMA-48 is guaranteed not to suffer from compatibility issues. That is, even if explicit hyperlinks aren't supported, the target URI is silently ignored and the supposed-to-be-visible text is displayed, without artifacts.

**Comment by magurotuna** [comment]
According to the design meeting held on July 8th (#11365), it seems like this feature is not what we should land. Close.

**Comment by ry** [comment]
@magurotuna Yes, I should have commented here already. We don't want to bloat the code with all of these nice-to-have terminal rendering features when a link to lint.deno.land would solve the problem.
