### ISSUE TITLE
Any documentation / roadmap autofix lint?

### ISSUE THREAD

**Issue by tamusjroyce** [denoland/deno_lint#763]
Any documentation / roadmap autofix link? Trying to finish a PR and was hoping some of the non-issue lint errors would be auto-fixed. I haven't done too much digging. So maybe autofix is a feature of deno lint command

**Comment by magurotuna** [comment]
Autofix is not yet implemented. I think its priority is relatively low so it will take a while to get it available.

**Comment by tamusjroyce** [comment]
Sounds good. Once [deno_wsc](https://github.com/nestdotland/deno_swc/pulls) is updated, might be easier. Turning minify to false in the example does a good job of formatting the code (code -> pure ast -> formatted code).

I think a little more needs exposed from rust to adjust 2 spaces instead of 4 and other tslint defined controlling variables. But it is a MVP sample to work from. If this is interesting to anyone. Let me know and I will try for a PR if you are interested.

**Comment by magurotuna** [comment]
I don't think I understand your idea so please correct me if I'm wrong, but is it that you will implement the auto-fix feature in TypeScript rather than Rust, using `deno_swc`? If it's correct, I don't think it's a good idea, because `deno_lint` needs to be a library written in Rust so that Deno CLI (which resides in https://github.com/denoland/deno) can depend on and make use of it.

> Question also being, should lint be used as a prettyfier? Or would this be better in a separate feature?

Linter and formatter should be separated in my opinion. ESLint, for instance, provides some basic functionality of formatter, resulting in conflict with other formatter (especially prettier) that we have to work around in some way.
Deno's built-in formatter and linter should do their own work well.

**Comment by tamusjroyce** [comment]
Excellent point. I completely agree it should be written in Rust. My point was that the example in deno_wsc (deno wrapper around ast) has a good example. No reason why we shouldn’t be able to easily do the same in Rust.

Great answer. Sounds like there are a lot of things outside of code that are blocking lint fix. So maybe even lint fix belongs as a different tool outside of lint? In any way, thanks for the info. It is helpful to know as I get more into it.

**Comment by magurotuna** [comment]
> So maybe even lint fix belongs as a different tool outside of lint?

I thought that integrating the auto-fix feature into deno_lint itself would be fine, but your idea also sounds good and reasonable. It would be something like receiving diagnostic results from the linter and performing the auto-fix to the code based on the results. This separation of responsibility would be really nice.

**Comment by tamusjroyce** [comment]
I was able to assist updating [deno_swc](https://github.com/nestdotland/deno_swc) to the latest (littledivy and wongjiahau did the heavy lifting). I am thinking deno_lint and deno_lint_typescript that would both be able to consume deno lint results. The typescript version would be extendable, per-project, using deno_swc to manipulate ast.

> Out of scope of this. But I am also thinking about ajv schema validation as an internal rust tool for deno. ajv is a json schema to javascript compiler. Unless there was some type debugging tool to profile object contents and verify if they fall within the typescript interfaces. That is just way out there. deno has such great potential.
