### ISSUE TITLE
Lint rule code - camelCase or kebab-case

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#82]
Currently rule codes are written using camelCase:
- `noExplicitAny`
- `noEval`
- `getterReturn`

In ESLint rule codes are written using kebab-case:
- `no-explicit-any`
- `no-eval`
- `getter-return`

Ignore directives are currently spelled out using kebab-case (`deno-lint-ignore` which follows convention from Deno for formatting ignores - `deno-fmt-ignore`).

We should make a decision one way or another and unify all codes.

Probably the best to go with kebab-case as it's already established convention in ESLint

**Comment by lucacasonato** [comment]
I vote for kebab case because ESLint uses it.

**Comment by crowlKats** [comment]
ye kebab-case would be the best to follow current existing conventions. keeps things just easier
