### ISSUE TITLE
New lint: `prefer-ascii` for Deno's internal JS

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno_lint#832]
Optimization around deno_core is being made now in https://github.com/denoland/deno/pull/9713. This optimization requires that all the JS code that is eventually bundled in Deno is fully written only in ASCII i.e. one-byte characters. So it would be great to have a new lint rule that makes sure of that.

Similar to `prefer-primordials`, the new lint will be dedicated to the internal of Deno. Not intended to be used by Deno users.

CC @AaronO @bartlomieju

**Comment by magurotuna** [comment]
I'd love to work on it

**Comment by grian32** [comment]
I believe this rule may also be of use to regular code, as you don't usually find yourself using chars outside of ASCII and if you do it might be a mistake(accidentally copy pasting a minus unicode character instead of `-` which while looking pretty similar, the minus unicode character is not valid javascript AFAIK).

**Comment by bartlomieju** [comment]
> I believe this rule may also be of use to regular code, as you don't usually find yourself using chars outside of ASCII and if you do it might be a mistake(accidentally copy pasting a minus unicode character instead of `-` which while looking pretty similar, the minus unicode character is not valid javascript AFAIK).

Once https://github.com/denoland/deno/pull/11776 lands it will be possible to enable this rule, but I don't think it should be part of "recommended" set

**Comment by grian32** [comment]
>  I don't think it should be part of "recommended" set
I agree @bartlomieju

**Comment by magurotuna** [comment]
I thought what @grian32 said made a lot of sense and tried to deal with characters outside of ASCII in JavaScript syntax, like the case where `‐` (this is _not_ an ASCII, unicode code point is U+2010) is placed at the position of binary operation. However, it seems like we can't handle this case, because swc only accepts valid JavaScript. Therefore, even without this rule, using `‐` (U+2010) mistakenly would be detected by running the linter as a result of the parse error.
