### ISSUE TITLE
Proposal: Control the execution order of `LintRule` trait

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno_lint#847]
### Context

Currently, `ban-unused-ignore` and `ban-unknown-rule-code` are handled specially since these rules have to be run after other rules. Moreover, there is a priority even in these two rules; `ban-unused-ignore` has to be run after `ban-unknown-rule-code`.
In short, we have to run lint rules in the following order:

1. normal rules (other than the two rules below) + plugins
2. `ban-unknown-rule-code`
3. `ban-unused-ignore`

To do this, the logics of these special rules are not implemented in `LintRule` trait, which I think may lead to the unnecessarily increasing complexity of the codebase.

### Solution

It would be a solution to add the information about the order of execution to `LintRule` trait. So `LintRule` trait would look like:

```rust
pub trait LintRule: std::fmt::Debug + Send + Sync {
  fn new() -> Box<Self> where Self: Sized;

  fn lint_program<'view>(
    &self,
    context: &mut Context<'view>,
    program: ProgramRef<'view>,
  );

  fn lint_program_with_ast_view<'view>(
    &self,
    context: &mut Context<'view>,
    program: Program<'view>,
  );

  fn code(&self) -> &'static str;

  fn tags(&self) -> &'static [&'static str];

  #[cfg(feature = "docs")]
  fn docs(&self) -> &'static str;

  // New method, which returns the priority of this rule.
  // The lower the return value is, the earlier this rule will be run.
  fn priority(&self) -> u32;
}
```

and then set the priorities like the following:

|rule type|priority|
|---------|-------|
|normal rules + plugins|0|
|`ban-unknown-rule-code`|1|
|`ban-unused-ignore`|2|

With this information, we could sort the execution order or lint rules, and would no longer need to implement the two rules in a special way. Also, if someday we have another special rule that needs to be run, say, between `ban-unknown-rule-code` and `ban-unused-ignore`, all we have to do would be just adjust the priority numbers.

**Comment by bartlomieju** [comment]
I'm in favor of this change 👍  thanks for a great write up @magurotuna. If we can make `ban-unknown-rule-code` and `ban-unused-ignore` into regular rules that's highly preferable.

**Comment by bartlomieju** [comment]
Unfortunately this change clashes a bit with #845; we can't borrow lint rules list mutable because it's behind and `Arc`. I think we might want to change #845 with use `Vec<Arc<dyn LintRule>>` instead.
