### ISSUE TITLE
deno -run_as_wasm code.ts

### ISSUE THREAD

**Issue by tysonrm** [denoland/deno_lint#923]
I'm still getting up to speed on deno so apologies in advance if something like this exists or it doesn't fit. The idea is to run your typescript in the wasm stack machine . That is, typescript that the assemblyscript compiler can compile to wasm

**Comment by lucacasonato** [comment]
TypeScript can not be compiled to WASM. AssemblyScript is a language that looks very similar to TypeScript, but is not the same.

Even if JS/TS could be compiled to WASM, it would not necessarily be faster.

See
- https://www.assemblyscript.org/frequently-asked-questions.html#is-webassembly-faster-than-javascript
- https://www.assemblyscript.org/frequently-asked-questions.html#will-assemblyscript-support-all-of-typescript-eventually

**Comment by caspervonb** [comment]
There's a subset of AssemblyScript that can run on both https://www.assemblyscript.org/portability.html#differences but as Luca said it doesn't work the other way around as the subset is really small.

Our ability to directly run wasm will be inline with the esm-integration proposal (https://github.com/WebAssembly/esm-integration/blob/master/proposals/esm-integration/README.md).

**Comment by tysonrm** [comment]
> TypeScript can not be compiled to WASM. AssemblyScript is a language that looks very similar to TypeScript, but is not the same.
> 
> Even if JS/TS could be compiled to WASM, it would not necessarily be faster.
> 
> See
> 
>     * https://www.assemblyscript.org/frequently-asked-questions.html#is-webassembly-faster-than-javascript
> 
>     * https://www.assemblyscript.org/frequently-asked-questions.html#will-assemblyscript-support-all-of-typescript-eventually

https://twitter.com/TysonMidboe/status/1447027500396253186?s=20
https://github.com/module-federation/aegis/blob/main/wasm/package.json

thanks guys
